### ISSUE TITLE
有Java版的么？

### ISSUE THREAD

**Issue by xq598359628** [foolchen/AndroidTracker#2]
同标题

**Comment by foolchen** [comment]
并没有Java版的，kotlin版本的在使用上与Java版的并没有太大区别。

**Comment by paozhuanyinyu** [comment]
是否考虑加一个java版本的，学习用

**Comment by foolchen** [comment]
如果增加Java版本的话成本就太高了，所以不会增加Java版本。
如果学习用的话，用kotlin版本应该也可以的，关键的逻辑我都有写注释，而且语法方面的规则跟Java差别不是很大。
